apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-calculator-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-calculator
  template:
    metadata:
      labels:
        app: java-calculator
    spec:
      containers:
      - name: java-calculator
        image: kotannithin/java-calculator:latest
        imagePullPolicy: Always
        stdin: true   # for interactive console (optional)
        tty: true     # for interactive console